production:
  clients:
    default:
      database: <%= "#{ENV['MONGODB_DB']}" %>
      hosts:
        - <%= "#{ENV['MONGODB_HOST1']}" %>
        - <%= "#{ENV['MONGODB_HOST2']}" %>
        - <%= "#{ENV['MONGODB_HOST3']}" %>
      options:
        write:
         w: 1
        read:
         mode: :secondary_preferred
         tag_sets:
           - use: web
        user: <%= "#{ENV['MONGODB_USER']}" %>
        password: <%= "#{ENV['MONGODB_PASS']}" %>
        roles:
         - 'dbOwner'
        auth_mech: :scram
        auth_source: admin
        replica_set: <%= "#{ENV['MONGODB_SHARD']}" %>
        ssl: true
  options:
    raise_not_found_error: false
development:
  clients:
    default:
      database: <%= "#{ENV['MONGODB_DB']}" %>
      hosts:
        - <%= "#{ENV['MONGODB_HOST1']}" %>
        - <%= "#{ENV['MONGODB_HOST2']}" %>
        - <%= "#{ENV['MONGODB_HOST3']}" %>
      options:
        write:
         w: 1
        read:
         mode: :secondary_preferred
         tag_sets:
           - use: web
        user: <%= "#{ENV['MONGODB_USER']}" %>
        password: <%= "#{ENV['MONGODB_PASS']}" %>
        roles:
         - 'dbOwner'
        auth_mech: :scram
        auth_source: admin
        replica_set: <%= "#{ENV['MONGODB_SHARD']}" %>
        ssl: true
  options:
    raise_not_found_error: false
test:
  clients:
    default:
      database: lospets_test
      hosts:
        - <%= "#{ENV['MONGODB_HOST1']}" %>
        - <%= "#{ENV['MONGODB_HOST2']}" %>
        - <%= "#{ENV['MONGODB_HOST3']}" %>
      options:
        write:
         w: 1
        read:
         mode: :secondary_preferred
         tag_sets:
           - use: web
        user: <%= "#{ENV['MONGODB_USER']}" %>
        password: <%= "#{ENV['MONGODB_PASS']}" %>
        roles:
         - 'dbOwner'
        auth_mech: :scram
        auth_source: admin
        replica_set: <%= "#{ENV['MONGODB_SHARD']}" %>
        ssl: true
  options:
    raise_not_found_error: false